### PR TITLE
Tested Percentage

### PR DESCRIPTION
**Pull request by Chorty**
Fixed change in UNIT_PERCENTAGE to just PERCENTAGE.

### CODE REVIEW

**Comment by Chorty** [comment]
No surprise there just remove "UNIT_" LOL

**Review by Chorty — COMMENTED** [review]
Done

**Comment by eseglem** [comment]
Sorry, apparently I need to work on my GitHub notifications. I only just saw this. Could you also update the `hacs.json` with the version where this changed?

**Comment by jes1417** [comment]
Can confirm manually changed in the file and was able to start the integration again.

**Pull request merged**
